-- Issue #18. PostgreSQL 15. Ejecutar sobre una base nueva y vacia.
-- Docker crea dinostar_rex mediante POSTGRES_DB y luego ejecuta este archivo
-- montado en /docker-entrypoint-initdb.d/init.sql. No hace falta CREATE DATABASE.
-- Los scripts de esa carpeta SOLO se ejecutan si el volumen de datos esta vacio.
-- Reiniciar un volumen existente NO aplica este esquema. No borrar datos para
-- actualizarlo: revisar el estado y preparar una migracion por separado (#22).
-- BEGIN/COMMIT evitan dejar parte del esquema si una instruccion SQL falla.
-- Ejecucion manual, exclusivamente sobre una base vacia:
--   psql -v ON_ERROR_STOP=1 -U dinostar -d dinostar_rex -f init.sql
-- No es un script de actualizacion ni se puede ejecutar dos veces sobre las
-- mismas tablas. No incluye DROP, datos de pacientes ni credenciales.
-- updated_at debe actualizarlo la aplicacion; DEFAULT solo actua al insertar.
-- Las FK enfermera_id verifican existencia del usuario, no su rol o estado.
-- La aplicacion debe validar esos permisos y sincronizar la resolucion de
-- alertas y sus atenciones mediante transacciones.
BEGIN;

-- ============================================================
-- DINOSTAR - ESQUEMA POSTGRESQL
-- Convención:
--   - snake_case
--   - PK/FK BIGINT
--   - fechas TIMESTAMPTZ
--   - eliminación lógica de usuarios/pacientes
--   - historial protegido con ON DELETE RESTRICT
-- ============================================================


-- ============================================================
-- 1. USUARIOS
-- ============================================================

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,

    rol VARCHAR(20) NOT NULL,
    turno VARCHAR(20),

    activo BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_usuarios_nombre
        CHECK (BTRIM(nombre) <> ''),

    CONSTRAINT chk_usuarios_email
        CHECK (
            BTRIM(email) <> ''
            AND email = LOWER(email)
        ),

    CONSTRAINT chk_usuarios_rol
        CHECK (
            rol IN ('ENFERMERA', 'ADMIN')
        ),

    CONSTRAINT chk_usuarios_turno
        CHECK (
            (rol = 'ADMIN' AND turno IS NULL)
            OR
            (
                rol = 'ENFERMERA'
                AND turno IS NOT NULL
                AND turno IN ('MATUTINO', 'VESPERTINO', 'NOCTURNO')
            )
        )
);


CREATE UNIQUE INDEX uq_usuarios_email
    ON usuarios (LOWER(email));


-- ============================================================
-- 2. PACIENTES
-- ============================================================

CREATE TABLE pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre VARCHAR(150) NOT NULL,
    numero_cama VARCHAR(20) NOT NULL,
    sala VARCHAR(50) NOT NULL,

    activo BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_pacientes_nombre
        CHECK (BTRIM(nombre) <> ''),

    CONSTRAINT chk_pacientes_numero_cama
        CHECK (BTRIM(numero_cama) <> ''),

    CONSTRAINT chk_pacientes_sala
        CHECK (BTRIM(sala) <> '')
);


-- Una cama solo puede pertenecer a un paciente activo.
-- LOWER evita que "A" y "a" se consideren salas diferentes.
CREATE UNIQUE INDEX uq_pacientes_cama_activa
    ON pacientes (
        LOWER(sala),
        LOWER(numero_cama)
    )
    WHERE activo = TRUE;


-- ============================================================
-- 3. ASIGNACIONES
-- ============================================================

CREATE TABLE asignaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    enfermera_id BIGINT NOT NULL,
    paciente_id BIGINT NOT NULL,

    turno VARCHAR(20) NOT NULL,

    fecha_inicio TIMESTAMPTZ NOT NULL,
    fecha_fin TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_asignaciones_enfermera
        FOREIGN KEY (enfermera_id)
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_asignaciones_paciente
        FOREIGN KEY (paciente_id)
        REFERENCES pacientes(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_asignaciones_turno
        CHECK (
            turno IN ('MATUTINO', 'VESPERTINO', 'NOCTURNO')
        ),

    CONSTRAINT chk_asignaciones_fechas
        CHECK (
            fecha_fin IS NULL
            OR fecha_fin >= fecha_inicio
        )
);


-- Solo una enfermera activa por paciente y por turno.
CREATE UNIQUE INDEX uq_asignacion_activa_paciente_turno
    ON asignaciones (paciente_id, turno)
    WHERE fecha_fin IS NULL;


CREATE INDEX idx_asignaciones_enfermera
    ON asignaciones (enfermera_id);

CREATE INDEX idx_asignaciones_paciente
    ON asignaciones (paciente_id);


-- ============================================================
-- 4. SESIONES
-- ============================================================

CREATE TABLE sesiones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    paciente_id BIGINT NOT NULL,
    enfermera_id BIGINT NOT NULL,

    vol_total DECIMAL(7,2) NOT NULL,

    modo_goteo VARCHAR(20) NOT NULL,
    estado VARCHAR(20) NOT NULL,

    inicio TIMESTAMPTZ NOT NULL,
    fin TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sesiones_paciente
        FOREIGN KEY (paciente_id)
        REFERENCES pacientes(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_sesiones_enfermera
        FOREIGN KEY (enfermera_id)
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_sesiones_vol_total
        CHECK (
            vol_total > 0
            AND vol_total <= 5000
        ),

    CONSTRAINT chk_sesiones_modo_goteo
        CHECK (
            modo_goteo IN (
                'NORMAL_GOTEO',
                'MICRO_GOTEO'
            )
        ),

    CONSTRAINT chk_sesiones_estado
        CHECK (
            estado IN (
                'ACTIVA',
                'PAUSADA',
                'FINALIZADA',
                'ERROR'
            )
        ),

    CONSTRAINT chk_sesiones_fechas
        CHECK (
            fin IS NULL
            OR fin >= inicio
        ),

    -- Una sesión finalizada debe tener fecha de fin.
    -- Las demás permanecen abiertas.
    CONSTRAINT chk_sesiones_estado_fin
        CHECK (
            (estado = 'FINALIZADA' AND fin IS NOT NULL)
            OR
            (estado <> 'FINALIZADA' AND fin IS NULL)
        )
);


-- ACTIVA y PAUSADA representan una sesión todavía en curso.
CREATE UNIQUE INDEX uq_sesion_en_curso_paciente
    ON sesiones (paciente_id)
    WHERE estado IN ('ACTIVA', 'PAUSADA');


CREATE INDEX idx_sesiones_paciente
    ON sesiones (paciente_id);

CREATE INDEX idx_sesiones_enfermera
    ON sesiones (enfermera_id);


-- ============================================================
-- 5. LECTURAS
-- ============================================================

CREATE TABLE lecturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sesion_id BIGINT NOT NULL,

    gotas_por_min INTEGER NOT NULL,
    vol_restante DECIMAL(7,2) NOT NULL,
    tiempo_restante_min INTEGER NOT NULL,

    timestamp_dispositivo TIMESTAMPTZ NOT NULL,

    -- Historial: la politica append-only debe aplicarse mediante permisos
    -- o logica de aplicacion; este esquema no bloquea UPDATE/DELETE por si solo.
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_lecturas_sesion
        FOREIGN KEY (sesion_id)
        REFERENCES sesiones(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_lecturas_gotas
        CHECK (
            gotas_por_min >= 0
            AND gotas_por_min <= 200
        ),

    CONSTRAINT chk_lecturas_vol_restante
        CHECK (
            vol_restante >= 0
            AND vol_restante <= 5000
        ),

    CONSTRAINT chk_lecturas_tiempo_restante
        CHECK (
            tiempo_restante_min >= 0
        )
);


CREATE INDEX idx_lecturas_sesion
    ON lecturas (sesion_id);

CREATE INDEX idx_lecturas_sesion_timestamp
    ON lecturas (sesion_id, timestamp_dispositivo);


-- ============================================================
-- 6. ALERTAS
-- ============================================================

CREATE TABLE alertas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sesion_id BIGINT NOT NULL,

    tipo VARCHAR(30) NOT NULL,
    mensaje VARCHAR(500) NOT NULL,

    resuelta BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_alertas_sesion
        FOREIGN KEY (sesion_id)
        REFERENCES sesiones(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_alertas_tipo
        CHECK (
            tipo IN (
                'FIN_BOLSA',
                'GOTEO_LENTO',
                'GOTEO_RAPIDO',
                'DESCONECTADO'
            )
        ),

    CONSTRAINT chk_alertas_mensaje
        CHECK (
            BTRIM(mensaje) <> ''
        )
);


CREATE INDEX idx_alertas_sesion
    ON alertas (sesion_id);

CREATE INDEX idx_alertas_pendientes
    ON alertas (sesion_id)
    WHERE resuelta = FALSE;


-- ============================================================
-- 7. ATENCIONES DE ALERTA
-- ============================================================

CREATE TABLE atenciones_alerta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    alerta_id BIGINT NOT NULL,
    enfermera_id BIGINT NOT NULL,

    notas VARCHAR(1000),

    resolvio BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_atenciones_alerta
        FOREIGN KEY (alerta_id)
        REFERENCES alertas(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_atenciones_enfermera
        FOREIGN KEY (enfermera_id)
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_atenciones_notas
        CHECK (
            notas IS NULL
            OR BTRIM(notas) <> ''
        )
);


CREATE INDEX idx_atenciones_alerta
    ON atenciones_alerta (alerta_id);

CREATE INDEX idx_atenciones_enfermera
    ON atenciones_alerta (enfermera_id);


-- Una alerta puede tener muchas atenciones,
-- pero solamente una puede ser la atención que la resolvió.
CREATE UNIQUE INDEX uq_atencion_resolutiva
    ON atenciones_alerta (alerta_id)
    WHERE resolvio = TRUE;


-- ============================================================
-- 8. LOGS DE AUDITORÍA
-- ============================================================

CREATE TABLE logs_auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Puede ser NULL cuando el evento fue generado
    -- automáticamente por el sistema.
    usuario_id BIGINT,

    accion VARCHAR(100) NOT NULL,
    tabla_afectada VARCHAR(100),
    registro_id BIGINT,

    datos_anteriores JSONB,
    datos_nuevos JSONB,

    -- Tipo nativo PostgreSQL para IPv4 / IPv6.
    ip INET,

    -- Historial de auditoria; requiere permisos para imponer append-only.
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_logs_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_logs_accion
        CHECK (
            BTRIM(accion) <> ''
        )
);


CREATE INDEX idx_logs_usuario
    ON logs_auditoria (usuario_id);

CREATE INDEX idx_logs_created_at
    ON logs_auditoria (created_at);

CREATE INDEX idx_logs_tabla_registro
    ON logs_auditoria (tabla_afectada, registro_id);


COMMIT;
