<?php

use App\Support\DomainSchema;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    public function up(): void
    {
        DomainSchema::apply('sesiones', $this->sql());
    }

    public function down(): void
    {
        DomainSchema::revert('sesiones');
    }

    public function sql(): string
    {
        return <<<'SQL'
CREATE TABLE sesiones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    paciente_id BIGINT NOT NULL,
    enfermera_id BIGINT NOT NULL,

    vol_total DECIMAL(7,2) NOT NULL,

    modo_goteo VARCHAR(20) NOT NULL,
    estado VARCHAR(20) NOT NULL,

    inicio TIMESTAMPTZ NOT NULL,
    fin TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sesiones_paciente
        FOREIGN KEY (paciente_id)
        REFERENCES pacientes(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_sesiones_enfermera
        FOREIGN KEY (enfermera_id)
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_sesiones_vol_total
        CHECK (
            vol_total > 0
            AND vol_total <= 5000
        ),

    CONSTRAINT chk_sesiones_modo_goteo
        CHECK (
            modo_goteo IN (
                'NORMAL_GOTEO',
                'MICRO_GOTEO'
            )
        ),

    CONSTRAINT chk_sesiones_estado
        CHECK (
            estado IN (
                'ACTIVA',
                'PAUSADA',
                'FINALIZADA',
                'ERROR'
            )
        ),

    CONSTRAINT chk_sesiones_fechas
        CHECK (
            fin IS NULL
            OR fin >= inicio
        ),

    CONSTRAINT chk_sesiones_estado_fin
        CHECK (
            (estado = 'FINALIZADA' AND fin IS NOT NULL)
            OR
            (estado <> 'FINALIZADA' AND fin IS NULL)
        )
);


CREATE UNIQUE INDEX uq_sesion_en_curso_paciente
    ON sesiones (paciente_id)
    WHERE estado IN ('ACTIVA', 'PAUSADA');


CREATE INDEX idx_sesiones_paciente
    ON sesiones (paciente_id);

CREATE INDEX idx_sesiones_enfermera
    ON sesiones (enfermera_id);
SQL;
    }
};
