<?php

use App\Support\DomainSchema;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    public function up(): void
    {
        DomainSchema::apply('logs_auditoria', $this->sql());
    }

    public function down(): void
    {
        DomainSchema::revert('logs_auditoria');
    }

    public function sql(): string
    {
        return <<<'SQL'
CREATE TABLE logs_auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    usuario_id BIGINT,

    accion VARCHAR(100) NOT NULL,
    tabla_afectada VARCHAR(100),
    registro_id BIGINT,

    datos_anteriores JSONB,
    datos_nuevos JSONB,

    ip INET,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_logs_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_logs_accion
        CHECK (
            BTRIM(accion) <> ''
        )
);


CREATE INDEX idx_logs_usuario
    ON logs_auditoria (usuario_id);

CREATE INDEX idx_logs_created_at
    ON logs_auditoria (created_at);

CREATE INDEX idx_logs_tabla_registro
    ON logs_auditoria (tabla_afectada, registro_id);
SQL;
    }
};
