<?php

use App\Support\DomainSchema;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    public function up(): void
    {
        DomainSchema::apply('usuarios', $this->sql());
    }

    public function down(): void
    {
        DomainSchema::revert('usuarios');
    }

    public function sql(): string
    {
        return <<<'SQL'
CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,

    rol VARCHAR(20) NOT NULL,
    turno VARCHAR(20),

    activo BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_usuarios_nombre
        CHECK (BTRIM(nombre) <> ''),

    CONSTRAINT chk_usuarios_email
        CHECK (
            BTRIM(email) <> ''
            AND email = LOWER(email)
        ),

    CONSTRAINT chk_usuarios_rol
        CHECK (
            rol IN ('ENFERMERA', 'ADMIN')
        ),

    CONSTRAINT chk_usuarios_turno
        CHECK (
            (rol = 'ADMIN' AND turno IS NULL)
            OR
            (
                rol = 'ENFERMERA'
                AND turno IS NOT NULL
                AND turno IN ('MATUTINO', 'VESPERTINO', 'NOCTURNO')
            )
        )
);


CREATE UNIQUE INDEX uq_usuarios_email
    ON usuarios (LOWER(email));
SQL;
    }
};
