<?php

use App\Support\DomainSchema;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    public function up(): void
    {
        DomainSchema::apply('pacientes', $this->sql());
    }

    public function down(): void
    {
        DomainSchema::revert('pacientes');
    }

    public function sql(): string
    {
        return <<<'SQL'
CREATE TABLE pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre VARCHAR(150) NOT NULL,
    numero_cama VARCHAR(20) NOT NULL,
    sala VARCHAR(50) NOT NULL,

    activo BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_pacientes_nombre
        CHECK (BTRIM(nombre) <> ''),

    CONSTRAINT chk_pacientes_numero_cama
        CHECK (BTRIM(numero_cama) <> ''),

    CONSTRAINT chk_pacientes_sala
        CHECK (BTRIM(sala) <> '')
);


CREATE UNIQUE INDEX uq_pacientes_cama_activa
    ON pacientes (
        LOWER(sala),
        LOWER(numero_cama)
    )
    WHERE activo = TRUE;
SQL;
    }
};
