<?php

use App\Support\DomainSchema;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    public function up(): void
    {
        DomainSchema::apply('lecturas', $this->sql());
    }

    public function down(): void
    {
        DomainSchema::revert('lecturas');
    }

    public function sql(): string
    {
        return <<<'SQL'
CREATE TABLE lecturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sesion_id BIGINT NOT NULL,

    gotas_por_min INTEGER NOT NULL,
    vol_restante DECIMAL(7,2) NOT NULL,
    tiempo_restante_min INTEGER NOT NULL,

    timestamp_dispositivo TIMESTAMPTZ NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_lecturas_sesion
        FOREIGN KEY (sesion_id)
        REFERENCES sesiones(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_lecturas_gotas
        CHECK (
            gotas_por_min >= 0
            AND gotas_por_min <= 200
        ),

    CONSTRAINT chk_lecturas_vol_restante
        CHECK (
            vol_restante >= 0
            AND vol_restante <= 5000
        ),

    CONSTRAINT chk_lecturas_tiempo_restante
        CHECK (
            tiempo_restante_min >= 0
        )
);


CREATE INDEX idx_lecturas_sesion
    ON lecturas (sesion_id);

CREATE INDEX idx_lecturas_sesion_timestamp
    ON lecturas (sesion_id, timestamp_dispositivo);
SQL;
    }
};
