<?php

use App\Support\DomainSchema;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    public function up(): void
    {
        DomainSchema::apply('alertas', $this->sql());
    }

    public function down(): void
    {
        DomainSchema::revert('alertas');
    }

    public function sql(): string
    {
        return <<<'SQL'
CREATE TABLE alertas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sesion_id BIGINT NOT NULL,

    tipo VARCHAR(30) NOT NULL,
    mensaje VARCHAR(500) NOT NULL,

    resuelta BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_alertas_sesion
        FOREIGN KEY (sesion_id)
        REFERENCES sesiones(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_alertas_tipo
        CHECK (
            tipo IN (
                'FIN_BOLSA',
                'GOTEO_LENTO',
                'GOTEO_RAPIDO',
                'DESCONECTADO'
            )
        ),

    CONSTRAINT chk_alertas_mensaje
        CHECK (
            BTRIM(mensaje) <> ''
        )
);


CREATE INDEX idx_alertas_sesion
    ON alertas (sesion_id);

CREATE INDEX idx_alertas_pendientes
    ON alertas (sesion_id)
    WHERE resuelta = FALSE;
SQL;
    }
};
