<?php

use App\Support\DomainSchema;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    public function up(): void
    {
        DomainSchema::apply('atenciones_alerta', $this->sql());
    }

    public function down(): void
    {
        DomainSchema::revert('atenciones_alerta');
    }

    public function sql(): string
    {
        return <<<'SQL'
CREATE TABLE atenciones_alerta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    alerta_id BIGINT NOT NULL,
    enfermera_id BIGINT NOT NULL,

    notas VARCHAR(1000),

    resolvio BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_atenciones_alerta
        FOREIGN KEY (alerta_id)
        REFERENCES alertas(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_atenciones_enfermera
        FOREIGN KEY (enfermera_id)
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_atenciones_notas
        CHECK (
            notas IS NULL
            OR BTRIM(notas) <> ''
        )
);


CREATE INDEX idx_atenciones_alerta
    ON atenciones_alerta (alerta_id);

CREATE INDEX idx_atenciones_enfermera
    ON atenciones_alerta (enfermera_id);


CREATE UNIQUE INDEX uq_atencion_resolutiva
    ON atenciones_alerta (alerta_id)
    WHERE resolvio = TRUE;
SQL;
    }
};
