<?php

use App\Support\DomainSchema;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    public function up(): void
    {
        DomainSchema::apply('asignaciones', $this->sql());
    }

    public function down(): void
    {
        DomainSchema::revert('asignaciones');
    }

    public function sql(): string
    {
        return <<<'SQL'
CREATE TABLE asignaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    enfermera_id BIGINT NOT NULL,
    paciente_id BIGINT NOT NULL,

    turno VARCHAR(20) NOT NULL,

    fecha_inicio TIMESTAMPTZ NOT NULL,
    fecha_fin TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_asignaciones_enfermera
        FOREIGN KEY (enfermera_id)
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_asignaciones_paciente
        FOREIGN KEY (paciente_id)
        REFERENCES pacientes(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_asignaciones_turno
        CHECK (
            turno IN ('MATUTINO', 'VESPERTINO', 'NOCTURNO')
        ),

    CONSTRAINT chk_asignaciones_fechas
        CHECK (
            fecha_fin IS NULL
            OR fecha_fin >= fecha_inicio
        )
);


CREATE UNIQUE INDEX uq_asignacion_activa_paciente_turno
    ON asignaciones (paciente_id, turno)
    WHERE fecha_fin IS NULL;


CREATE INDEX idx_asignaciones_enfermera
    ON asignaciones (enfermera_id);

CREATE INDEX idx_asignaciones_paciente
    ON asignaciones (paciente_id);
SQL;
    }
};
